### ISSUE TITLE
Title Screen Theme is inaccurate so i made it accurate

### ISSUE THREAD

**Issue by Refrigigeggrtor** [stalechilibeans/teste#1]
https://streamable.com/42meww

**Comment by stalechilibeans** [comment]
Bro i opened this repository to find the differences between vanilla sm64 and tpp v1 cos of smth i'm working on but this is so good bro 😭😭 try it out on my chili-tpp repository or smth and send a vid

**Comment by stalechilibeans** [comment]
Ur using the vanilla tpp one which doesnt even sound alike

**Comment by stalechilibeans** [comment]
sure mate

**Comment by stalechilibeans** [comment]
sendd it or smthhh idkkk lol

**Comment by stalechilibeans** [comment]
BRUUUH ok bro fine

**Comment by stalechilibeans** [comment]
jjjjj BROOO u have access now ee
